### ISSUE TITLE
Models missing `siteId` property after version 2.0 release 

### ISSUE THREAD

**Issue by josh-biddick** [ricado-group/js-api-client#142]
Just rolling out the latest `@ricado/api-client` I noticed many models are now missing the `siteId` property.

I've noticed this so far on the `PermanentObjectModel` and `PackrunModel` classes.
 
![image](https://user-images.githubusercontent.com/74222743/149679010-ca0bbc60-534c-47c7-8097-637327b28b9b.png)

![image](https://user-images.githubusercontent.com/74222743/149679026-79918c4a-e7a9-45bb-a4b8-0cd7a93f1457.png)

![image](https://user-images.githubusercontent.com/74222743/149679043-6f66069b-1877-4763-9572-b3524feab0ef.png)

I saw a comment here from a recent commit - https://github.com/ricado-group/js-api-client/commit/123a32c7e9fcb185e71fb99c3ecc7faf873b94a1

What was the reason for this change? Any chance we can re-introduce this property?

**Comment by ashneilson** [comment]
@josh-biddick I believe we had discussed this a while back when considering making the JS API Client models basic objects and avoiding the use of getters and setters: https://github.com/ricado-group/js-api-client/issues/46

Now the models are plain objects and match the structure of the API specification exactly.

There is no `siteId` property on API responses since you must provide the `siteId` in the request anyhow.

https://ricado-group.github.io/php-rest-api-docs/

We could look at introducing it back in if it requires a lot of re-work. It was originally intended to be a "helper" property to make the developers life easier (not having to keep a record of siteId somewhere else).

**Comment by josh-biddick** [comment]
@ashneilson Yeah, I thought there was something we discussed a while back. 

I think it would be fine to omit it for newer apps where we're we have clear way to fetch and structure data. However, for the Packhouse Reporting App there still seems to be decent chunk of the code that relies on the `siteId` being there. We could refactor the code base but it would be pretty involved as it's how the data has been structured in the first place. 

Bearing in mind the we're going to need the new endpoint for Packrun Infeed Reports, we could either introduce that endpoint to v1 or re-introduce the `siteId` in v2?

**Comment by ashneilson** [comment]
@josh-biddick I'll close this for now and we can start a discussion on the Packhouse Reporting App to decide best approach there 👍
