### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by michaelpeterlee** [ricado-group/js-api-client#33]
NodeJS v12.21.0

Steps to reproduce:

Upgraded the following libraries, then npm install.
OLD: "@ricado/api-client": "^1.2.1"
NEW: "@ricado/api-client": "^1.2.3"

![image](https://user-images.githubusercontent.com/19398181/121832614-90faca80-cd1e-11eb-870d-f91071e9c017.png)

Possible solutions:

1. Consumers to amend their Babel config by including different presets

**Comment by ashneilson** [comment]
@michaelpeterlee There was an update to API Client and Core-UI which changed the browsers we supported and allowed us to make use of Tree-Shaking when bundling using Webpack.

The Gen 4 Accounts Web App has the necessary changes (which are only a couple of minor ones) in order to get the builds working again.

Did you want to review and make changes yourself? Otherwise I could submit a simple PR with the changes.

**Comment by michaelpeterlee** [comment]
@ashneilson `gen4-accounts-web` consists of multiple commits. I changed tsconfig to no-avail. I'm happy to review a commit that resolves this elsewhere, or as a PR for this repo.

**Comment by ashneilson** [comment]
@michaelpeterlee I'm going to recommend that @josh-biddick assists you with this build error given that `gen4-accounts-web` has further changes that Josh will need to help with migrating in this PR 🙂

**Comment by josh-biddick** [comment]
Closing this as it should be resolved with a conversation
